name: Testing CI
on:
  push:
  pull_request:
    branches:
    - main

jobs:
  test-erato-gb:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: |
          mkdir -p ./roms/
          wget https://github.com/mattcurrie/dmg-acid2/releases/download/v1.0/dmg-acid2.gb -O ./roms/dmg-acid2.gb
          touch ./src/assets/bootroms/cgb_boot.bin
          touch ./src/assets/bootroms/dmg_boot.bin
      - run: zig build test --summary all

